# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackathonBD-WeSpeak' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackathonBD-WeSpeak
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.3'
  pod 'OpenTok'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'RPCircularProgress', '~> 0.3.0'
  pod 'Cosmos', '~> 11.0'
  pod 'FlagKit'
end
